spring:
  kafka:
    client-id: kafka-stream
    consumer:
      auto-offset-reset: earliest
---
kafka:
  topic:
    source: source
    store: output-store
    reward: output-reward
    pattern: output-pattern
